name: Build Fabric mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew
        working-directory: df-mob-visualizer-build

      - name: Build mod
        run: ./gradlew clean build --no-daemon --stacktrace
        working-directory: df-mob-visualizer-build

      - uses: actions/upload-artifact@v4
        with:
          name: df-mob-visualizer
          path: df-mob-visualizer-build/build/libs/*.jar
